## This notebook include code for camparing accruacy with and without replacing emoji with words.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
emotion_scores =[]
sentiment_scores =[]
for i in range(12):
    file_path = f"emotion_scores_{i}.txt"
    with open(file_path,"r") as file:
        emotions = eval(file.read())
    #print(len(emotions))
    emotion_scores.extend(emotions)

print(len(emotion_scores))
for i in range(12):
    file_path = f"sentiment_scores_{i}.txt"
    with open(file_path,"r") as file:
        sentiments = eval(file.read())
    #print(len(emotions))
    sentiment_scores.extend(sentiments)

print(len(sentiment_scores))
import numpy as np
import pandas as pd

import pandas as pd
train_df = pd.read_csv('submission_train.csv')
samuels_pred_df = pd.read_csv('training_no_duplicates.csv')
num_rows =1127644
# Split the DataFrame into two parts
first_part = train_df.iloc[:num_rows]
second_part = train_df.iloc[num_rows:]

print(len(first_part))
print(len(second_part))
print(len(first_part)+len(second_part))
# Concatenate the second part first, followed by the first part
train_df = pd.concat([second_part, first_part]).reset_index(drop=True)
fe = emotion_scores[:1127644]
se = emotion_scores[1127644:]
emotion_score_swapped = se + fe
print(len(emotion_score_swapped))

fs = sentiment_scores[:1127644]
ss = sentiment_scores[1127644:]
sentiment_score_swapped = ss + fs
train_df.loc[:, 'emotion_scores'] = emotion_score_swapped

train_df.loc[:, 'sentiment_scores2'] = sentiment_score_swapped

train_df.loc[:, 'sentiment_scores'] = samuels_pred_df['predictions']
train_df.loc[:, 'sentiment_scores'] = train_df.loc[:, 'sentiment_scores'].replace(0,-1)
train_df.loc[:, 'emoji_scores'] = train_df['emoji_scores'].replace(0, np.nan)
train_df.loc[:,'spam_score'] = train_df['spam_score'].replace(0,np.nan)
train_df.loc[:,'fake_lables'] = train_df['fake_lables'].replace(0,np.nan)
train_df.loc[:,'spam_score']= train_df['spam_score'].replace(1,-1)
def modify_value(x):
    if x == 0.0 or np.isnan(x):
        return np.nan
    elif x > 0.0:
        return 1
    else:
        return -1
train_df.loc[:, 'emoji_scores'] = train_df['emoji_scores'].apply(modify_value)
train_df.loc[:, 'vadar'] = train_df['vadar'].apply(modify_value)

In [ ]:
from sklearn.metrics import accuracy_score,precision_score, recall_score
from sklearn.metrics import confusion_matrix
accuracy_sam = accuracy_score(train_df['label'], train_df['sentiment_scores2'])
precision_sam = precision_score(train_df['label'], train_df['sentiment_scores2'])
recall_sam = recall_score(train_df['label'], train_df['sentiment_scores2'])
precision_sam_neg = precision_score(train_df['label'], train_df['sentiment_scores2'],pos_label =-1)
recall_sam_neg = recall_score(train_df['label'], train_df['sentiment_scores2'],pos_label =-1)
cm = confusion_matrix(train_df['label'], train_df['sentiment_scores2'])
print(cm)
print(f"accuracy: {accuracy_sam:.4f}")
print(f"precision_pos: {precision_sam:.4f}")
print(f"recall_pos: {recall_sam:.4f}")
print(f"precision_neg: {precision_sam_neg:.4f}")
print(f"recall_neg: {recall_sam_neg:.4f}")

In [ ]:

vader_scores = train_df['vadar']
vadar_score_cal_df = pd.DataFrame({'label': train_df['label'], 'vader_scores': vader_scores})
# Filter out rows where the 'vader_scores' is NaN
filtered_df = vadar_score_cal_df.dropna(subset=['vader_scores'])
print(f"length of non-np.nan elements {len(filtered_df)/2270482}")
print(f"length of pos elements {len(filtered_df[filtered_df['vader_scores']==1])/len(filtered_df)}")
print(f"length of neg elements {len(filtered_df[filtered_df['vader_scores']==-1])/len(filtered_df)}")
# Compute accuracy only on non-NaN values
accuracy = accuracy_score(filtered_df['label'], filtered_df['vader_scores'])
from sklearn.metrics import accuracy_score,precision_score, recall_score
accuracy_sam = accuracy_score(filtered_df['label'], filtered_df['vader_scores'])
precision_sam = precision_score(filtered_df['label'], filtered_df['vader_scores'])
recall_sam = recall_score(filtered_df['label'], filtered_df['vader_scores'])
precision_sam_neg = precision_score(filtered_df['label'], filtered_df['vader_scores'],pos_label =-1)
recall_sam_neg = recall_score(filtered_df['label'], filtered_df['vader_scores'],pos_label =-1)

cm = confusion_matrix(filtered_df['label'], filtered_df['vader_scores'])
print(cm)
print(f"accuracy: {accuracy_sam:.2f}")
print(f"precision_pos: {precision_sam:.2f}")
print(f"recall_pos: {recall_sam:.2f}")
print(f"precision_neg: {precision_sam_neg:.2f}")
print(f"recall_neg: {recall_sam_neg:.2f}")

In [ ]:
from sklearn.metrics import accuracy_score,precision_score, recall_score
accuracy_sam = accuracy_score(train_df['label'], train_df['emotion_scores'])
precision_sam = precision_score(train_df['label'], train_df['emotion_scores'])
recall_sam = recall_score(train_df['label'], train_df['emotion_scores'])
precision_sam_neg = precision_score(train_df['label'], train_df['emotion_scores'],pos_label =-1)
recall_sam_neg = recall_score(train_df['label'], train_df['emotion_scores'],pos_label =-1)

cm = confusion_matrix(train_df['label'], train_df['emotion_scores'])
print(cm)
print(f"accuracy: {accuracy_sam:.4f}")
print(f"precision_pos: {precision_sam:.4f}")
print(f"recall_pos: {recall_sam:.4f}")
print(f"precision_neg: {precision_sam_neg:.4f}")
print(f"recall_neg: {recall_sam_neg:.4f}")

## Now without emoji replacement

In [ ]:
emotion_scores =[]
sentiment_scores =[]
for i in range(12):
    file_path = f"new_pipeline_emotion_scores_{i}.txt"
    with open(file_path,"r") as file:
        emotions = eval(file.read())
    #print(len(emotions))
    emotion_scores.extend(emotions)

print(len(emotion_scores))
for i in range(12):
    file_path = f"new_pipeline_sentiment_scores_{i}.txt"
    with open(file_path,"r") as file:
        sentiments = eval(file.read())
    #print(len(emotions))
    sentiment_scores.extend(sentiments)

print(len(sentiment_scores))
import numpy as np
import pandas as pd

import pandas as pd
train_df = pd.read_csv('final_train_with_vadar.csv')
samuels_pred_df = pd.read_csv('training_no_duplicates.csv')
num_rows =1127644
# Split the DataFrame into two parts
first_part = train_df.iloc[:num_rows]
second_part = train_df.iloc[num_rows:]

print(len(first_part))
print(len(second_part))
print(len(first_part)+len(second_part))
# Concatenate the second part first, followed by the first part
train_df = pd.concat([second_part, first_part]).reset_index(drop=True)
fe = emotion_scores[:1127644]
se = emotion_scores[1127644:]
emotion_score_swapped = se + fe
print(len(emotion_score_swapped))

fs = sentiment_scores[:1127644]
ss = sentiment_scores[1127644:]
sentiment_score_swapped = ss + fs
train_df.loc[:, 'emotion_scores'] = emotion_score_swapped

train_df.loc[:, 'sentiment_scores2'] = sentiment_score_swapped

train_df.loc[:, 'sentiment_scores'] = samuels_pred_df['predictions']
train_df.loc[:, 'sentiment_scores'] = train_df.loc[:, 'sentiment_scores'].replace(0,-1)
train_df.loc[:, 'emoji_scores'] = train_df['emoji_scores'].replace(0, np.nan)
train_df.loc[:,'spam_score'] = train_df['spam_score'].replace(0,np.nan)
train_df.loc[:,'fake_lables'] = train_df['fake_lables'].replace(0,np.nan)
train_df.loc[:,'spam_score']= train_df['spam_score'].replace(1,-1)
def modify_value(x):
    if x == 0.0 or np.isnan(x):
        return np.nan
    elif x > 0.0:
        return 1
    else:
        return -1
train_df.loc[:, 'emoji_scores'] = train_df['emoji_scores'].apply(modify_value)
train_df.loc[:, 'vadar'] = train_df['vadar'].apply(modify_value)

2270482
2270482
1127644
1142838
2270482
2270482


In [ ]:
from sklearn.metrics import accuracy_score,precision_score, recall_score
from sklearn.metrics import confusion_matrix
accuracy_sam = accuracy_score(train_df['label'], train_df['sentiment_scores2'])
precision_sam = precision_score(train_df['label'], train_df['sentiment_scores2'])
recall_sam = recall_score(train_df['label'], train_df['sentiment_scores2'])
precision_sam_neg = precision_score(train_df['label'], train_df['sentiment_scores2'],pos_label =-1)
recall_sam_neg = recall_score(train_df['label'], train_df['sentiment_scores2'],pos_label =-1)
cm = confusion_matrix(train_df['label'], train_df['sentiment_scores2'])
print(cm)
print(f"accuracy: {accuracy_sam:.4f}")
print(f"precision_pos: {precision_sam:.4f}")
print(f"recall_pos: {recall_sam:.4f}")
print(f"precision_neg: {precision_sam_neg:.4f}")
print(f"recall_neg: {recall_sam_neg:.4f}")

[[654688 488150]
 [238427 889217]]
accuracy: 0.6800
precision_pos: 0.6456
recall_pos: 0.7886
precision_neg: 0.7330
recall_neg: 0.5729


In [ ]:
from sklearn.metrics import accuracy_score,precision_score, recall_score
accuracy_sam = accuracy_score(train_df['label'], train_df['emotion_scores'])
precision_sam = precision_score(train_df['label'], train_df['emotion_scores'])
recall_sam = recall_score(train_df['label'], train_df['emotion_scores'])
precision_sam_neg = precision_score(train_df['label'], train_df['emotion_scores'],pos_label =-1)
recall_sam_neg = recall_score(train_df['label'], train_df['emotion_scores'],pos_label =-1)

cm = confusion_matrix(train_df['label'], train_df['emotion_scores'])
print(cm)
print(f"accuracy: {accuracy_sam:.4f}")
print(f"precision_pos: {precision_sam:.4f}")
print(f"recall_pos: {recall_sam:.4f}")
print(f"precision_neg: {precision_sam_neg:.4f}")
print(f"recall_neg: {recall_sam_neg:.4f}")

[[580606 562232]
 [191264 936380]]
accuracy: 0.6681
precision_pos: 0.6248
recall_pos: 0.8304
precision_neg: 0.7522
recall_neg: 0.5080


In [ ]:
old_vadar_score_df = pd.read_csv('full_df_big_deprecated.csv')
old_vadar_score_df.loc[:, 'vadar'] = old_vadar_score_df['vadar'].apply(modify_value)
vader_scores = old_vadar_score_df['vadar']

In [ ]:
print(vader_scores_swapped)

0          1.0
1          1.0
2         -1.0
3         -1.0
4         -1.0
          ... 
2270477   -1.0
2270478    1.0
2270479    1.0
2270480    1.0
2270481    1.0
Name: vadar, Length: 2270482, dtype: float64


In [ ]:
first_part = vader_scores.iloc[:num_rows]
second_part = vader_scores.iloc[num_rows:]

vader_scores_swapped = pd.concat([second_part, first_part]).reset_index(drop=True)

In [ ]:
old_vadar_score_df.head()

Unnamed: 0                                               line  label  \
0           0  <user> i dunno justin read my mention or not ....      1   
1           1  because your logic is so dumb , i will not eve...      1   
2           2  <user> just put casper in a box ! looved the b...      1   
3           3  <user> <user> thanks sir > > do not trip lil m...      1   
4           4  visiting my brother tmr is the bestest birthda...      1   

   emoji_scores  spam_score  fake_lables   vadar  
0             0           0            0  0.6597  
1             0           0            0 -0.6418  
2             0           0            0 -0.7896  
3             0           0            0  0.4926  
4             0           0            0  0.5826

In [ ]:
vadar_score_cal_df = pd.DataFrame({'label': train_df['label'], 'vader_scores': vader_scores_swapped})
# Filter out rows where the 'vader_scores' is NaN
filtered_df = vadar_score_cal_df.dropna(subset=['vader_scores'])
print(f"length of non-np.nan elements {len(filtered_df)/2270482}")
print(f"length of pos elements {len(filtered_df[filtered_df['vader_scores']==1])/len(filtered_df)}")
print(f"length of neg elements {len(filtered_df[filtered_df['vader_scores']==-1])/len(filtered_df)}")
# Compute accuracy only on non-NaN values
accuracy = accuracy_score(filtered_df['label'], filtered_df['vader_scores'])
from sklearn.metrics import accuracy_score,precision_score, recall_score
accuracy_sam = accuracy_score(filtered_df['label'], filtered_df['vader_scores'])
precision_sam = precision_score(filtered_df['label'], filtered_df['vader_scores'])
recall_sam = recall_score(filtered_df['label'], filtered_df['vader_scores'])
precision_sam_neg = precision_score(filtered_df['label'], filtered_df['vader_scores'],pos_label =-1)
recall_sam_neg = recall_score(filtered_df['label'], filtered_df['vader_scores'],pos_label =-1)

cm = confusion_matrix(filtered_df['label'], filtered_df['vader_scores'])
print(cm)
print(f"accuracy: {accuracy_sam:.2f}")
print(f"precision_pos: {precision_sam:.2f}")
print(f"recall_pos: {recall_sam:.2f}")
print(f"precision_neg: {precision_sam_neg:.2f}")
print(f"recall_neg: {recall_sam_neg:.2f}")

length of non-np.nan elements 0.7463719157430009
length of pos elements 0.677930915648545
length of neg elements 0.322069084351455
[[414129 414532]
 [131657 734306]]
accuracy: 0.68
precision_pos: 0.64
recall_pos: 0.85
precision_neg: 0.76
recall_neg: 0.50
